name: Deploy to Azure

on:
  # push:
  #   branches:
  #     - main  # Runs deployment when code is pushed to "main"
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group crud-play-RG \
            --template-file backend/pipeline/main.bicep \
            --parameters sqlAdmin=${{ secrets.SQL_ADMIN }} sqlPassword=${{ secrets.SQL_ADMIN_PASSWORD }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build & Publish
        run: |
          dotnet publish backend/CrudPlay.Api/CrudPlay.Api.csproj -c Release -o out

      - name: Deploy .NET Web API
        run: |
          az webapp deploy --name crud-play-api --resource-group crud-play-RG --src-path out/

      - name: Logout from Azure
        run: az logout
